# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\notepad.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.theme_resources import resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 450)
        MainWindow.setMinimumSize(QtCore.QSize(500, 450))
        MainWindow.setMaximumSize(QtCore.QSize(500, 450))
        with open('./ui/theme_resources/stylesheet.qss', 'r', encoding='utf8') as f:
            MainWindow.setStyleSheet(f.read())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_encrypt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/document-encrypted.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_encrypt.setIcon(icon)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.horizontalLayout.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/document-decrypt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_decrypt.setIcon(icon1)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.horizontalLayout.addWidget(self.btn_decrypt)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 50, 480, 390))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.btn_copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy.setGeometry(QtCore.QRect(410, 29, 80, 22))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/edit-copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_copy.setIcon(icon2)
        self.btn_copy.setObjectName("btn_copy")
        self.btn_copy.raise_()
        self.horizontalLayoutWidget.raise_()
        self.plainTextEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notepad Encryption"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Enter a message to encrypt or decrypt..."))
        self.btn_copy.setText(_translate("MainWindow", "Copy"))
